### PR TITLE
Retry failed runs with ObserveAndDelete policy

### LINKED ISSUE #295: Retry failed runs with ObserveAndDelete policy
### What problem are you facing?

When using the default ObserveAndDelete policy, ansible failures are never retried.  When a playbook (or role or command) runs for the first time, even if a transient error was encountered, it will be saved in the last-applied-configuration annotation and, on the next reconciliation cycle, provider-ansible won't attempt to run ansible it the spec didn't change compared to last-applied-configuration.
Imagine a scenario where, for example, the run failed b/c some VM in its inventory was unreachable. One would expect that, once the underlying VM issue is fixed, the run sould self-heal like most k8s resources, but that's not what happens.

Note that retries of failed runs do happed with the CheckWhenObserve policy.

### How could Crossplane help solve your problem?

Whenever provider-ansible finds that the last run failed, it could re-run the playbook/role/command even if there were no differences compared to the last-applied-configuration. There are many ways to accomplish it. One example is to check the ReconcileSuccess condition. If getting stuck in a retry loop is a concern, exponential backoff can be introduced by setting status fields or annotations containing the last backoff period.

Happy to work on this if y'all don't hate the idea :)

### PR DESCRIPTION
**Pull request by d-honeybadger**
### Description of your changes

Fixes #295
On backoff: Since `Observe` returns error whenever a retry run fails, crossplane-runtime will [automatically apply backoff](https://github.com/crossplane/crossplane-runtime/blob/e0bda77c3c946bfe0914cd871143038ad32a13bc/pkg/reconciler/managed/reconciler.go#L917)
We don't have control over the interval, max steps etc., but it's going to be the same default backoff that crossplane-runtime applies whenever `Update` fails, so we should have the bahavior that matches `CheckWhenObserve` policy's updates, and also matches other providers.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### How has this code been tested

1. Deploy modified version of provider-ansible in a k8s cluster (make local.xpkg.deploy.provider.provider-ansible)
2. Create an ansiblerun w/ the default run policy ObserveAndDelete and a playbook that will fail. Here's my example:
```
apiVersion: ansible.crossplane.io/v1alpha1
kind: AnsibleRun
metadata:
  annotations:
  name: test-run
spec:
  forProvider:
    executableInventory: false
    inventoryInline: |
      cluster:
        hosts:
          test:
            ansible_host: <VM IP>
    playbookInline: |
      - hosts: cluster
        tasks:
        - file:
            path: /test-file-missing
            state: present
    vars:
      ansible_ssh_private_key_file: ./ssh_id
  providerConfigRef:
    name: test-config
3. Watch the logs to see retries
4. Fix the playbook, e.g.:
 playbookInline: |
      - hosts: cluster
        tasks:
        - file:
            path: /test-file-missing
            state: touch
5. Check the logs to see that, after a successful run, no more runs happen during regular sync.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: cmd/provider/main.go [hunk 1]
```diff
@@ -42,6 +43,7 @@ func main() {
 		timeout                = app.Flag("timeout", "Controls how long Ansible processes may run before they are killed.").Default("20m").Duration()
 		leaderElection         = app.Flag("leader-election", "Use leader election for the controller manager.").Short('l').Default("false").OverrideDefaultFromEnvar("LEADER_ELECTION").Bool()
 		maxReconcileRate       = app.Flag("max-reconcile-rate", "The maximum number of concurrent reconciliation operations.").Default("1").Int()
+		retryFailed            = app.Flag("retry-failed", "Whether to retry failed runs with ObserveAndDelete policy (with CheckWhenObserve, they are retried unconditionally).").Default("false").Bool()
```
Comment (d-honeybadger) [inline cmd/provider/main.go:46]: Idk if this flag is a good idea: retrying failed syncs, to me, is something that a k8s controller should always do, it shouldn't even be configurable. And it's unconditionally retried with CheckWhenObserve policy.
But there might be provider-ansible users who already rely on the existing no-retries behavior, which is the only reason I added the flag. LMK what you'd prefer

File: cmd/provider/main.go [hunk 2]
```diff
@@ -76,6 +78,13 @@ func main() {
 		Features:                &feature.Flags{},
 	}
 
-	kingpin.FatalIfError(ansible.Setup(mgr, o, *ansibleCollectionsPath, *ansibleRolesPath, *timeout), "Cannot setup Ansible controllers")
+	ao := ansiblerun.SetupOptions{
```
Comment (d-honeybadger) [inline cmd/provider/main.go:81]: The list of parameters that apply only to the ansiblerun controller and not to the config controller was getting too long as I added another flag, so I decided to refactor a bit and out this into a struct

File: internal/controller/ansibleRun/ansibleRun.go [hunk 3]
```diff
@@ -448,41 +456,41 @@ func getLastAppliedParameters(observed *v1alpha1.AnsibleRun) (*v1alpha1.AnsibleR
...
+	isUpToDate := (lastParameters != nil && equality.Semantic.DeepEqual(*lastParameters, desired.Spec.ForProvider))
+
+	isLastSyncOK := (desired.GetCondition(xpv1.TypeSynced).Status == v1.ConditionTrue)
+
+	if isUpToDate && isLastSyncOK {
+		// nothing to do for this run
+		return managed.ExternalObservation{ResourceExists: true, ResourceUpToDate: true}, nil
 	}
 
-	if !isUpToDate {
```
Comment (d-honeybadger) [inline internal/controller/ansibleRun/ansibleRun.go:459]: This whole block has just changed indentation cause it was moved out of the `if`. There aren't actually any logic changes

**Comment by d-honeybadger** [comment]
@morningspace ready for review :pray:

**Comment by morningspace** [comment]
@d-honeybadger There are some lint errors and conflicts need to be resolved.

File: cmd/provider/main.go (hunk 1 above)
Comment (d-honeybadger) [reply cmd/provider/main.go]: :facepalm: yup forgot to consume it in `handleLastApplied`
Anyway, removed the flag

**Comment by d-honeybadger** [comment]
@morningspace sorry about the linting errors! Turns out I commented out the linting line in the makefile cause at some point it was broken for me, and of course forgot that I did that...
Got it working now and all linting passing

**Review by morningspace — APPROVED** [review]
It looks awesome.
